In [1]:
import numpy as np

# --- Вхідні дані ---
n = 4  # Введи сюди свій номер за списком!
size = n + 2

print(f"Варіант (n): {n}")
print(f"Розмірність матриць: {size}x{size}")

# 1. Створення двох двовимірних масивів з випадковими числами від 0 до 9 [cite: 24, 280]
# Використовуємо np.random.randint для цілих чисел
matrix_1 = np.random.randint(0, 10, (size, size))
matrix_2 = np.random.randint(0, 10, (size, size))

print("\nМатриця 1:\n", matrix_1)
print("\nМатриця 2:\n", matrix_2)

# 2. Арифметичні операції [cite: 49-57, 281]
add_res = np.add(matrix_1, matrix_2)      # Додавання
sub_res = np.subtract(matrix_1, matrix_2) # Віднімання
# Додаємо маленьке число, щоб уникнути ділення на нуль
div_res = np.divide(matrix_1, matrix_2 + 1e-10) 

# Скалярне множення (матричний добуток) [cite: 58, 59]
dot_res = np.dot(matrix_1, matrix_2)

# Векторне множення (поелементне) [cite: 54, 55]
mult_res = np.multiply(matrix_1, matrix_2)

print("\n--- Результати операцій ---")
print("Сума (перший рядок):\n", add_res[0])
print("Скалярний добуток (dot):\n", dot_res[0])
print("Поелементне множення:\n", mult_res[0])

# 3. Лінійна алгебра для matrix_1 [cite: 68-75, 282]
from scipy import linalg

det = linalg.det(matrix_1) # Визначник
try:
    inv = linalg.inv(matrix_1) # Обернена матриця
except linalg.LinAlgError:
    inv = "Матриця вироджена (визначник = 0)"

eigenvalues, eigenvectors = linalg.eig(matrix_1) # Власні числа та вектори

print("\n--- Лінійна алгебра (для Матриці 1) ---")
print(f"Визначник: {det:.2f}")
print("Власні числа:\n", eigenvalues)

Варіант (n): 4
Розмірність матриць: 6x6

Матриця 1:
 [[7 1 7 3 0 2]
 [0 4 7 4 2 4]
 [9 9 1 9 3 6]
 [9 2 5 3 4 3]
 [5 0 2 3 7 1]
 [0 0 7 6 0 4]]

Матриця 2:
 [[1 3 5 5 6 5]
 [7 4 9 7 3 4]
 [3 9 9 6 7 8]
 [9 1 3 0 1 7]
 [9 1 5 8 8 9]
 [8 5 4 0 7 6]]

--- Результати операцій ---
Сума (перший рядок):
 [ 8  4 12  8  6  7]
Скалярний добуток (dot):
 [ 78 101 124  84 111 128]
Поелементне множення:
 [ 7  3 35 15  0 10]

--- Лінійна алгебра (для Матриці 1) ---
Визначник: 32036.00
Власні числа:
 [24.14234114+0.j        -8.65476446+0.j        -2.0532532 +0.j
  5.12101726+2.4312939j  5.12101726-2.4312939j  2.32364199+0.j       ]


In [2]:
from scipy import optimize, integrate
from scipy.misc import derivative
import numpy as np

# Визначення функції з Варіанту 4 (Таблиця 1.1)
def f(x):
    # ln^2(x) / x -> (log(x)**2) / x
    return (np.log(x)**2) / x

point = 2.0
interval = [1.0, 4.0]

# 1. Похідна в точці x = 2.0 [cite: 79-84]
# dx - крок для обчислення похідної
der = derivative(f, point, dx=1e-6)
print(f"Похідна в точці {point}: {der:.5f}")

# 2. Первісна (визначений інтеграл) на проміжку [1.0, 4.0] [cite: 85-88]
integral_val, error = integrate.quad(f, interval[0], interval[1])
print(f"Інтеграл на проміжку {interval}: {integral_val:.5f}")

# 3. Оптимізація (мінімуми) [cite: 94-103]
# Шукаємо локальний мінімум, починаючи з точки 0.5 (зліва) та 3.0 (справа)
res_min_global = optimize.minimize(f, x0=0.5, bounds=[(0.1, 5)]) 
res_min_local = optimize.minimize(f, x0=3.0, bounds=[(0.1, 5)])

# Для наочності знайдемо максимум (мінімізуємо -f(x))
def neg_f(x): return -f(x)
res_max = optimize.minimize(neg_f, x0=2.0, bounds=[(0.1, 5)])

print(f"Глобальний мінімум (x): {res_min_global.x[0]:.2f}, f(x): {res_min_global.fun:.2f}")
print(f"Максимум функції (x): {res_max.x[0]:.2f} (Приблизно e -> 2.718)")

Похідна в точці 2.0: 0.22646
Інтеграл на проміжку [1.0, 4.0]: 0.88807
Глобальний мінімум (x): 1.00, f(x): 0.00
Максимум функції (x): 5.00 (Приблизно e -> 2.718)


C:\Users\porsh\AppData\Local\Temp\ipykernel_7976\2993659546.py:15: DeprecationWarning: scipy.misc.derivative is deprecated in SciPy v1.10.0; and will be completely removed in SciPy v1.12.0. You may consider using findiff: https://github.com/maroba/findiff or numdifftools: https://github.com/pbrod/numdifftools
  der = derivative(f, point, dx=1e-6)


In [3]:
import pandas as pd

n = 4 # Твій номер
size_p = n + 1

# 1. Створення Series з вільно заданими мітками [cite: 119]
data_values = [10, 20, 30, 40, 50] # 5 значень для n=4
custom_index = ['a', 'b', 'c', 'd', 'e']
series_obj = pd.Series(data_values, index=custom_index)

# 2. Створення словника та Series з нього [cite: 121-122]
data_dict = {'Kyiv': 100, 'Lviv': 85, 'Odessa': 90, 'Kharkiv': 80, 'Dnipro': 75}
cities_series = pd.Series(data_dict)

print("--- Pandas Series ---")
print(cities_series)

# 3. Операції (індексація, фільтрація, зміна) [cite: 123-135]
print("\nЗначення по ключу 'Kyiv':", cities_series['Kyiv'])
print("Фільтрація (значення < 90):\n", cities_series[cities_series < 90])

# Арифметичні операції
print("\nМноження значень на 2:\n", cities_series * 2)

--- Pandas Series ---
Kyiv       100
Lviv        85
Odessa      90
Kharkiv     80
Dnipro      75
dtype: int64

Значення по ключу 'Kyiv': 100
Фільтрація (значення < 90):
 Lviv       85
Kharkiv    80
Dnipro     75
dtype: int64

Множення значень на 2:
 Kyiv       200
Lviv       170
Odessa     180
Kharkiv    160
Dnipro     150
dtype: int64


In [ ]:
import pandas as pd
import numpy as np

# 1. Завантаження [cite: 145]
df = pd.read_csv('titanic.csv')

print("--- ЗАВДАННЯ 6: Базові операції ---")

# 2. Огляд даних (Head/Tail/Shape) [cite: 148-152]
print(f"Розмірність датасету: {df.shape}")
print("\nПерші 3 рядки:\n", df.head(3))
print("\nОстанні 3 рядки:\n", df.tail(3))

# 3. Типи даних та колонки [cite: 154-156]
print("\nТипи даних:\n", df.dtypes)

--- ЗАВДАННЯ 6: Базові операції ---
Розмірність датасету: (891, 12)

Перші 3 рядки:
    PassengerId  Survived  Pclass                                               Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0            1         0       3                            Braund, Mr. Owen Harris    male  22.0      1      0         A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1      0          PC 17599  71.2833   C85        C
2            3         1       3                             Heikkinen, Miss. Laina  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S

Останні 3 рядки:
      PassengerId  Survived  Pclass                                      Name     Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1      2  W./C. 6607  23.45   NaN        S
88

In [ ]:

# 4. Вибір конкретних стовпців [cite: 159]
print("\nТільки імена та клас каюти:\n", df[['Name', 'Pclass']].head())

# 5. Індексація loc та iloc [cite: 160-171]
print("\nДані 10-го пасажира (iloc):\n", df.iloc[10])
print("\nЗріз даних (loc): рядки 5-8, стовпці Name та Age:\n", df.loc[5:8, ['Name', 'Age']])



Тільки імена та клас каюти:
                                                 Name  Pclass
0                            Braund, Mr. Owen Harris       3
1  Cumings, Mrs. John Bradley (Florence Briggs Th...       1
2                             Heikkinen, Miss. Laina       3
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
4                           Allen, Mr. William Henry       3

Дані 10-го пасажира (iloc):
 PassengerId                                 11
Survived                                     1
Pclass                                       3
Name           Sandstrom, Miss. Marguerite Rut
Sex                                     female
Age                                        4.0
SibSp                                        1
Parch                                        1
Ticket                                 PP 9549
Fare                                      16.7
Cabin                                       G6
Embarked                                     S
Sex_Code  

In [ ]:

# 6. Фільтрація (Маски) [cite: 172-175]
# Шукаємо жінок (Sex== 'female') старших за 50 років
filtered_df = df[(df['Sex'] == 'female') & (df['Age'] > 50)]
print(f"\nКількість жінок старше 50 років: {len(filtered_df)}")

# 7. Статистика (Describe, Value Counts) [cite: 176-183]
print("\nСтатистика по числових полях:\n", df.describe())
print("\nКількість пасажирів у кожному класі:\n", df['Pclass'].value_counts())



Кількість жінок старше 50 років: 17

Статистика по числових полях:
        PassengerId    Survived      Pclass         Age       SibSp       Parch        Fare    Sex_Code    Fare_USD
count   891.000000  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008    0.381594   32.204208    0.352413   41.865470
std     257.353842    0.486592    0.836071   14.526497    1.102743    0.806057   49.693429    0.477990   64.601457
min       1.000000    0.000000    1.000000    0.420000    0.000000    0.000000    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000    0.000000    7.910400    0.000000   10.283520
50%     446.000000    0.000000    3.000000   28.000000    0.000000    0.000000   14.454200    0.000000   18.790460
75%     668.500000    1.000000    3.000000   38.000000    1.000000    0.000000   31.000000    1.000000   40.300000
max     891

In [7]:

print("\n--- ЗАВДАННЯ 7: Групування та Перетворення ---")

# 8. Групування (Groupby) [cite: 198-215]
# Групуємо за класом каюти (Pclass) та рахуємо середню вартість квитка (Fare) і середній вік (Age)
grouped = df.groupby(['Pclass'])[['Fare', 'Age']].mean()
print("\nСередня ціна та вік по класах:\n", grouped)

# Агрегація з кількома функціями (agg) [cite: 220-224]
# Для віку шукаємо мінімум і максимум у кожному класі
agg_res = df.groupby(['Pclass']).agg({'Age': ['min', 'max'], 'Fare': 'mean'})
print("\nМін. і макс. вік по класах:\n", agg_res)

# 9. Перетворення ознак (Map/Apply) [cite: 265-275]
# map: Перетворимо текстову стать у числову (male=0, female=1)
sex_map = {'male': 0, 'female': 1}
df['Sex_Code'] = df['Sex'].map(sex_map)

# apply: Конвертуємо ціну квитка з фунтів у долари (умовно * 1.3)
df['Fare_USD'] = df['Fare'].apply(lambda x: x * 1.3)

print("\nРезультат перетворення (нові стовпці):\n", df[['Name', 'Sex', 'Sex_Code', 'Fare', 'Fare_USD']].head())


--- ЗАВДАННЯ 7: Групування та Перетворення ---

Середня ціна та вік по класах:
              Fare        Age
Pclass                      
1       84.154687  38.233441
2       20.662183  29.877630
3       13.675550  25.140620

Мін. і макс. вік по класах:
          Age             Fare
         min   max       mean
Pclass                       
1       0.92  80.0  84.154687
2       0.67  70.0  20.662183
3       0.42  74.0  13.675550

Результат перетворення (нові стовпці):
                                                 Name     Sex  Sex_Code     Fare  Fare_USD
0                            Braund, Mr. Owen Harris    male         0   7.2500   9.42500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female         1  71.2833  92.66829
2                             Heikkinen, Miss. Laina  female         1   7.9250  10.30250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female         1  53.1000  69.03000
4                           Allen, Mr. William Henry    male         0   

In [8]:
import pandas as pd

# 1. Завантаження трьох таблиць [cite: 235]
# calendar.csv - доступність житла по датах
# listings.csv - опис квартир
# reviews.csv - відгуки користувачів
try:
    calendar = pd.read_csv('calendar.csv')
    listings = pd.read_csv('listings.csv')
    reviews = pd.read_csv('reviews.csv')
    print("Файли успішно завантажено!")
except FileNotFoundError:
    print("Помилка: Переконайтеся, що файли (calendar.csv, listings.csv, reviews.csv) знаходяться в папці.")

# 2. Попередній огляд
print("Listings shape:", listings.shape)
print("Reviews shape:", reviews.shape)

# --- MERGE (Злиття) --- [cite: 242-249]
# З'єднаємо описи квартир (listings) з відгуками про них (reviews).
# У listings ключ 'id', у reviews ключ 'listing_id'.
# Використовуємо 'inner', щоб отримати тільки ті квартири, які мають відгуки.

merged_data = pd.merge(
    listings[['id', 'name', 'price', 'neighbourhood']], # беремо тільки потрібні стовпці
    reviews[['listing_id', 'reviewer_name', 'comments']], 
    left_on='id', 
    right_on='listing_id', 
    how='inner'
)

print("\n--- Результат MERGE (Квартири + Відгуки) ---")
print(merged_data.head())


# --- JOIN (Приєднання за індексом) --- [cite: 252-256]
# Для join нам потрібно встановити індекси.
# Давайте приєднаємо календар (ціни та дати) до лістингів.

# Встановлюємо 'id' як індекс для listings
listings_indexed = listings.set_index('id')

# Встановлюємо 'listing_id' як індекс для calendar
calendar_indexed = calendar.set_index('listing_id')

# Об'єднуємо. Оскільки рядків дуже багато, візьмемо тільки перші 100 для прикладу
# lsuffix/rsuffix потрібні, якщо є однакові назви колонок
joined_data = listings_indexed.head(100).join(
    calendar_indexed.head(100), 
    lsuffix='_info', 
    rsuffix='_schedule'
)

print("\n--- Результат JOIN (Квартири + Календар) ---")
# Виводимо назву квартири (з лівої таблиці) і дату/доступність (з правої)
print(joined_data[['name', 'date', 'available']].head())

Файли успішно завантажено!
Listings shape: (3585, 95)
Reviews shape: (68275, 6)

--- Результат MERGE (Квартири + Відгуки) ---
        id                               name   price neighbourhood  listing_id reviewer_name                                           comments
0  3075044  Charming room in pet friendly apt  $65.00    Roslindale     3075044       Dmitrii  Andrea is a great host. Neighborhood is wonder...
1  3075044  Charming room in pet friendly apt  $65.00    Roslindale     3075044         Paola  We had a great time at Andrea's place. He is v...
2  3075044  Charming room in pet friendly apt  $65.00    Roslindale     3075044        Jaydee  Adrea was very welcoming and flexible to our n...
3  3075044  Charming room in pet friendly apt  $65.00    Roslindale     3075044       Anthony  Andrea made us feel welcome because he made th...
4  3075044  Charming room in pet friendly apt  $65.00    Roslindale     3075044         Xinny  Me and my friend were so happy about Andrea's ...

---

In [9]:
import pandas as pd

# Завантаження таблиць
try:
    drivers = pd.read_csv('drivers.csv')
    races = pd.read_csv('races.csv')
    results = pd.read_csv('results.csv')
    print("Файли Формули-1 завантажено.")
except FileNotFoundError:
    print("Помилка: переконайтеся, що файли drivers.csv, races.csv, results.csv є в папці.")

# Огляд ключів
# drivers має 'driverId'
# races має 'raceId'
# results має і 'driverId', і 'raceId' — це зв'язуюча ланка

# [cite_start]--- MERGE (Об'єднання таблиць) [cite: 227-249] ---
# Завдання: Дізнатися імена водіїв, які приїхали першими (positionOrder = 1)
# З'єднуємо results (результати) з drivers (імена) по 'driverId'

# Спочатку відфільтруємо тільки переможців, щоб таблиця була меншою
winners_only = results[results['positionOrder'] == 1]

# Merge
winners_names = pd.merge(
    winners_only[['resultId', 'raceId', 'driverId']], # Ліва таблиця
    drivers[['driverId', 'forename', 'surname', 'nationality']], # Права таблиця
    on='driverId', # Ключ
    how='inner'
)

print("\n--- Результат MERGE (Переможці гонок) ---")
print(winners_names.head())


# [cite_start]--- JOIN (Приєднання за індексом) [cite: 251-258] ---
# Завдання: Додати до таблиці переможців назву траси та рік.
# Використовуємо 'raceId' як індекс для з'єднання.

# Встановлюємо індекси
winners_indexed = winners_names.set_index('raceId')
races_indexed = races.set_index('raceId')

# Join: до результатів додаємо інформацію про гонку
full_info = winners_indexed.join(
    races_indexed[['year', 'name']], # Беремо тільки рік і назву траси
    rsuffix='_race' # Суфікс на випадок однакових колонок (хоча тут їх немає)
)

print("\n--- Результат JOIN (Переможець + Назва траси) ---")
# Виводимо рік, трасу і ім'я переможця
print(full_info[['year', 'name', 'forename', 'surname']].sort_values('year').tail())

Файли Формули-1 завантажено.

--- Результат MERGE (Переможці гонок) ---
   resultId  raceId  driverId forename    surname nationality
0         1      18         1    Lewis   Hamilton     British
1        23      19         8     Kimi  Räikkönen     Finnish
2        45      20        13   Felipe      Massa   Brazilian
3        67      21         8     Kimi  Räikkönen     Finnish
4        89      22        13   Felipe      Massa   Brazilian

--- Результат JOIN (Переможець + Назва траси) ---
        year                      name forename     surname
raceId                                                     
1123    2024     Australian Grand Prix   Carlos       Sainz
1122    2024  Saudi Arabian Grand Prix      Max  Verstappen
1121    2024        Bahrain Grand Prix      Max  Verstappen
1131    2024       Austrian Grand Prix   George     Russell
1144    2024      Abu Dhabi Grand Prix    Lando      Norris


In [10]:
import pandas as pd

# Налаштування для гарного відображення таблиць
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

print("\n" + "="*50)
print("   ЗАВДАННЯ 8: MOVIELENS (ФІЛЬМИ + РЕЙТИНГИ)")
print("="*50)

# 1. Завантаження даних
try:
    movies = pd.read_csv('movies.csv')
    ratings = pd.read_csv('ratings.csv')
    links = pd.read_csv('links.csv')
    print(">>> Файли movies, ratings та links успішно завантажено.")
except FileNotFoundError:
    print("!!! Помилка: Не знайдено файли (movies.csv, ratings.csv, links.csv).")

# Огляд розмірності
print(f"Фільмів: {movies.shape[0]}, Рейтингів: {ratings.shape[0]}")

# --- 2. MERGE (Об'єднання за спільним стовпцем) [cite: 227-249] ---
# У таблиці 'ratings' є тільки ID фільму, але немає назви.
# У таблиці 'movies' є ID і назва.
# Давайте об'єднаємо їх, щоб бачити, якому фільму поставили 5 зірок.

# Беремо тільки високі оцінки (5.0), щоб таблиця була меншою
top_ratings = ratings[ratings['rating'] == 5.0].head(100) # Беремо перші 100 п'ятірок

# Об'єднуємо (merge) таблицю оцінок з таблицею фільмів по 'movieId'
merged_movies = pd.merge(
    top_ratings[['userId', 'movieId', 'rating']], # Ліва таблиця (оцінки)
    movies[['movieId', 'title', 'genres']],       # Права таблиця (назви)
    on='movieId',                                 # Ключ
    how='inner'
)

print("\n>>> Результат MERGE (Користувачі та їхні улюблені фільми):")
print(merged_movies[['userId', 'rating', 'title']].head())


# --- 3. JOIN (Приєднання за індексом)  ---
# У нас є таблиця 'links', яка містить посилання на IMDB.
# Давайте приєднаємо ці посилання до нашої таблиці фільмів 'movies'.
# Для join нам потрібні однакові індекси.

# Встановлюємо 'movieId' як індекс для обох таблиць
movies_indexed = movies.set_index('movieId')
links_indexed = links.set_index('movieId')

# Приєднуємо links до movies
# Використовуємо lsuffix/rsuffix, хоча тут колонки унікальні, це хороша практика
movies_with_links = movies_indexed.join(
    links_indexed,
    lsuffix='_mov',
    rsuffix='_lnk'
)

print("\n>>> Результат JOIN (Фільми + ID з IMDB):")
# Виводимо назву і код IMDB для перших 5 фільмів
print(movies_with_links[['title', 'imdbId', 'tmdbId']].head())

# Додатково: збережемо результат для звіту
movies_with_links.head(20).to_csv('movies_final_report.csv')
print("\n>>> Звіт збережено у 'movies_final_report.csv'")


   ЗАВДАННЯ 8: MOVIELENS (ФІЛЬМИ + РЕЙТИНГИ)
>>> Файли movies, ratings та links успішно завантажено.
Фільмів: 9742, Рейтингів: 100836

>>> Результат MERGE (Користувачі та їхні улюблені фільми):
   userId  rating                        title
0       1     5.0  Seven (a.k.a. Se7en) (1995)
1       1     5.0   Usual Suspects, The (1995)
2       1     5.0         Bottle Rocket (1996)
3       1     5.0               Rob Roy (1995)
4       1     5.0        Canadian Bacon (1995)

>>> Результат JOIN (Фільми + ID з IMDB):
                                      title  imdbId   tmdbId
movieId                                                     
1                          Toy Story (1995)  114709    862.0
2                            Jumanji (1995)  113497   8844.0
3                   Grumpier Old Men (1995)  113228  15602.0
4                  Waiting to Exhale (1995)  114885  31357.0
5        Father of the Bride Part II (1995)  113041  11862.0

>>> Звіт збережено у 'movies_final_report.csv'
